version: '3.8'
services:
  movies:
    image: mupparaju0007/paytmmovies:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
  train:
    image: mupparaju0007/paytmtrain:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  dth:
    image: mupparaju0007/paytmdth:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  recharge:
    image: mupparaju0007/paytmrecharge:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
