version: '3.8'
services:
  movies:
    image: mupparaju0009/paytmmovies:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  train:
    image: mupparaju0009/paytmtrain:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  dth:
    image: mupparaju0009/paytmdth:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
  recharge:
    image: mupparaju0009/paytmrecharge:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3

